name: dosbox-x
adopt-info: dosbox-x
summary:  DOSBox-X fork of the DOSBox project
base: core18
description: |
  DOSBox-X is a x86 emulator with Tandy/Hercules/CGA/EGA/VGA/SVGA graphics
  sound and DOS. It's been designed to run old DOS games under platforms that
  don't support it.

architectures:
  - build-on: i386
  - build-on: amd64

confinement: strict
grade: stable

apps:
  dosbox-x:
    command: desktop-launch $SNAP/dosbox-x
    plugs: [network, network-bind, unity7, opengl, home, pulseaudio, desktop, desktop-legacy, removable-media]

parts:
  dosbox-x:
    plugin: autotools
    after: [desktop-glib-only]
    source-type: git
    source: https://github.com/joncampbell123/dosbox-x.git
    override-build: |
        # There is no pattern in the release tags for DosBox-X
        # This should resolve to a version or datestamp or both.
        last_committed_tag="$(git describe --tags --abbrev=0)"
        last_committed_tag_ver="$(echo ${last_committed_tag} | sed -e 's/dosbox-x-//' -e 's/wip-//' -e 's/windows-//' -e 's/v//')"
        last_released_tag="$(snap info dosbox-x | awk '$1 == "beta:" { print $2 }')"
        # If the latest tag from the upstream project has not been released to
        # beta, build that tag instead of master.
        if [ "${last_committed_tag_ver}" != "${last_released_tag}" ]; then
          git fetch
          git checkout "${last_committed_tag}"
        fi
        # ./build-debug-no-avcodec
        ./build
        cp src/dosbox-x $SNAPCRAFT_PART_INSTALL
        snapcraftctl set-version $(git -C ../src describe --tags | sed -e 's/dosbox-x-//' -e 's/wip-//' -e 's/windows-//' -e 's/v//')
    build-packages:
      - g++
      - make
      - libsdl1.2-dev
      - libpng-dev
      - libsdl-net1.2-dev
      - libsdl-sound1.2-dev
      - libasound2-dev
      - libxkbfile-dev
      - nasm
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libswscale-dev
    stage-packages:
      - libnuma1
      - libogg0
      - libopus0
      - libsoxr0
      - libtwolame0
      - libxcb-dri2-0
      - libxcb-dri3-0
      - libxcb-glx0
      - libxcb-present0
      - libzvbi0
      - libglu1-mesa
      - libva2
      - libasound2
      - libcrystalhd3
      - libfontconfig1
      - libpng16-16
      - libgme0
      - libgsm1
      - libmp3lame0
      - liborc-0.4-0
      - librtmp1
      - libshine3
      - libsnappy1v5
      - libspeex1
      - libssh-gcrypt-4
      - libtheora0
      - libvorbis0a
      - libvorbisenc2
      - libwavpack1
      - libxkbfile1
      - libxml2
      - libxvidcore4
      - libavcodec57
      - libavformat57
      - libavutil55
      - libbluray2
      - libmodplug1
      - libjpeg62
#      - libschroedinger-1.0-0
      - libswresample2
      - libswscale4
      - libvpx5
      - libwebp6
      - libx264-152
      - libx265-146
  desktop-glib-only:
    build-packages:
      - libglib2.0-dev
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    stage-packages:
      - libglib2.0-bin
